<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW0942" ignored="0" name="Test" tests="12" failures="11" timestamp="2019-12-02T19:29:18 MSK" time="0.051" errors="0">
  <testcase name="checkSquare" time="0.007" classname="Tests.QuadratTest">
    <failure type="org.testng.TestException" message="
Method QuadratTest.checkSquare(java.lang.Double)[pri:0, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadratTest.checkSquare(java.lang.Double)[pri:0, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.QuadratTest">
    <failure type="org.testng.TestException" message="
Method QuadratTest.checkSquare(java.lang.Double)[pri:0, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadratTest.checkSquare(java.lang.Double)[pri:0, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.QuadratTest">
    <failure type="org.testng.TestException" message="
Method QuadratTest.checkSquare(java.lang.Double)[pri:0, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadratTest.checkSquare(java.lang.Double)[pri:0, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkPerimetr" time="0.0" classname="Tests.QuadratTest">
    <failure type="org.testng.TestException" message="
Method QuadratTest.checkPerimetr(java.lang.Double)[pri:1, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadratTest.checkPerimetr(java.lang.Double)[pri:1, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkPerimetr -->
  <testcase name="checkPerimetr" time="0.0" classname="Tests.QuadratTest">
    <failure type="org.testng.TestException" message="
Method QuadratTest.checkPerimetr(java.lang.Double)[pri:1, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadratTest.checkPerimetr(java.lang.Double)[pri:1, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkPerimetr -->
  <testcase name="checkPerimetr" time="0.0" classname="Tests.QuadratTest">
    <failure type="org.testng.TestException" message="
Method QuadratTest.checkPerimetr(java.lang.Double)[pri:1, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method QuadratTest.checkPerimetr(java.lang.Double)[pri:1, instance:Tests.QuadratTest@6d7b4f4c] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkPerimetr -->
  <testcase name="checkCircumference" time="0.001" classname="Tests.CircleTest">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Tests.CircleTest.checkCircumference(java.lang.Double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkCircumference([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 1.0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Tests.CircleTest.checkCircumference(java.lang.Double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkCircumference([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 1.0]
at java.util.ArrayList.forEach(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- checkCircumference -->
  <testcase name="checkSquare" time="0.0" classname="Tests.CircleTest">
    <skipped/>
  </testcase> <!-- checkSquare -->
  <testcase name="checkPerimetr" time="0.001" classname="Tests.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkPerimetr(java.lang.Double, java.lang.Double)[pri:1, instance:Tests.RectangleTest@13a5fe33] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkPerimetr(java.lang.Double, java.lang.Double)[pri:1, instance:Tests.RectangleTest@13a5fe33] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkPerimetr -->
  <testcase name="checkPerimetr" time="0.002" classname="Tests.RectangleTest">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Tests.RectangleTest.checkPerimetr(java.lang.Double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkPerimetr([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000,(java.lang.Double) 2.0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Tests.RectangleTest.checkPerimetr(java.lang.Double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkPerimetr([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000,(java.lang.Double) 2.0]
at java.util.ArrayList.forEach(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- checkPerimetr -->
  <testcase name="checkRectangle" time="0.001" classname="Tests.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkRectangle(java.lang.Double, java.lang.Double)[pri:1, instance:Tests.RectangleTest@13a5fe33] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkRectangle(java.lang.Double, java.lang.Double)[pri:1, instance:Tests.RectangleTest@13a5fe33] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkRectangle -->
  <testcase name="checkRectangle" time="0.001" classname="Tests.RectangleTest">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Tests.RectangleTest.checkRectangle(java.lang.Double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkRectangle([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000,(java.lang.Double) 2.0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Tests.RectangleTest.checkRectangle(java.lang.Double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkRectangle([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000,(java.lang.Double) 2.0]
at java.util.ArrayList.forEach(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- checkRectangle -->
</testsuite> <!-- Test -->
