<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW0942" ignored="0" name="testing" tests="52" failures="15" timestamp="2019-12-23T15:58:55 MSK" time="0.084" errors="0">
  <testcase name="checkCircl" time="0.007" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkCircl" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkCircl" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkCircumference" time="0.001" classname="Tests.TestFigures.CircleTest">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Tests.TestFigures.CircleTest.checkCircumference(double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkCircumference([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=)]}, Parameter{index=1, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Double) 2.0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Tests.TestFigures.CircleTest.checkCircumference(double,java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Arguments: [(java.lang.Double) 2.0]
at java.util.ArrayList.forEach(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- checkCircumference -->
  <testcase name="checkRectangle" time="0.003" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [20000.0] but found [1.0E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [20000.0] but found [1.0E8]
at Tests.TestFigures.RectangleTest.checkRectangle(RectangleTest.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkRectangle -->
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [5.0] but found [6.25]">
      <![CDATA[java.lang.AssertionError: did not expect to find [5.0] but found [6.25]
at Tests.TestFigures.RectangleTest.checkRectangle(RectangleTest.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkRectangle -->
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.RectangleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [25000.0] but found [1.0E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [25000.0] but found [1.0E8]
at Tests.TestFigures.RectangleTest.checkRectangle(RectangleTest.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkRectangle -->
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.0" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.RectangleTest"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.CircleTest"/>
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.CircleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [19.635] but found [19.636]">
      <![CDATA[java.lang.AssertionError: did not expect to find [19.635] but found [19.636]
at Tests.TestFigures.CircleTest.checkSquare(CircleTest.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.0" classname="Tests.TestFigures.CircleTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [3.14159265359E8] but found [3.1415926536E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [3.14159265359E8] but found [3.1415926536E8]
at Tests.TestFigures.CircleTest.checkSquare(CircleTest.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkSquare -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkQuadrat(double, double)[pri:2, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkQuadrat(double, double)[pri:2, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Is not Square&amp;quot; but got &amp;quot;The values aren&amp;apos;t the same&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Is not Square" but got "The values aren't the same"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.RuntimeException: The values aren't the same
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:48)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Is not Square&amp;quot; but got &amp;quot;The values aren&amp;apos;t the same&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Is not Square" but got "The values aren't the same"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.RuntimeException: The values aren't the same
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:48)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Is not Square&amp;quot; but got &amp;quot;The values aren&amp;apos;t the same&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Is not Square" but got "The values aren't the same"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.RuntimeException: The values aren't the same
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:48)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkQuadrat(double, double)[pri:2, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkQuadrat(double, double)[pri:2, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Is not Square&amp;quot; but got &amp;quot;The values aren&amp;apos;t the same&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Is not Square" but got "The values aren't the same"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.RuntimeException: The values aren't the same
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:48)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Is not Square&amp;quot; but got &amp;quot;The values aren&amp;apos;t the same&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Is not Square" but got "The values aren't the same"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.RuntimeException: The values aren't the same
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:48)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.0" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;Is not Square&amp;quot; but got &amp;quot;The values aren&amp;apos;t the same&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Is not Square" but got "The values aren't the same"
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.RuntimeException: The values aren't the same
at Tests.TestFigures.RectangleTest.checkQuadrat(RectangleTest.java:48)
... 22 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkQuadrat" time="0.001" classname="Tests.TestFigures.RectangleTest">
    <failure type="org.testng.TestException" message="
Method RectangleTest.checkQuadrat(double, double)[pri:2, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method RectangleTest.checkQuadrat(double, double)[pri:2, instance:Tests.TestFigures.RectangleTest@6325a3ee, instance params:[]] should have thrown an exception of type class java.lang.RuntimeException
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkQuadrat -->
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.0" classname="Tests.TestFigures.Figures"/>
  <testcase name="checkRectangle" time="0.001" classname="Tests.TestFigures.Figures"/>
</testsuite> <!-- testing -->
